WIP Query Store Directly
mozilla-prototypes/sync-storage-prototype pull request #68
Opened 2018-03-29 14:55 UTC by fluffyemily

Android and iOS draft 1 of FFI for direct Mentat querying.

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/Item.java
> +        if(this.dueDate == null) {
Nit: space before `(` throughout.

`:%s,if(,if (,g`

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/Item.java
>      private Long dueDate;
Any reason not to keep this as a `Date`, simplifying the rest of the code?

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/ItemsCallback.java
> +package com.mozilla.toodle;
License block.

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/JNA.java
> +    Pointer col_at_index(Pointer rows, int index);
Shouldn't these all be `value_at_index` or `get_value`?

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/JNA.java
> +    Pointer column_iter(Pointer rows);
I'm not sure about the word 'column'. 'Coll' results consist of items or values. A 'rel' row contains bindings or values.

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Query.java
> +package com.mozilla.toodle.rust;
License block.

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Query.java
> +        if(this.rawPointer == null) {
Spacing throughout.

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Query.java
> +                    Log.i("Query", result.err);
`Log.e`?

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Query.java
> +        new Thread(new Runnable() {
We shouldn't standardize this kind of thread-spawning pattern.

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/QueryResultListHandler.java
> +package com.mozilla.toodle.rust;
License blocks throughout all of these files.

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/QueryResultValueHandler.java
> +public interface QueryResultValueHandler {
These might be clearer if they used scalar/coll/rel/tuple instead of value/list/rows/row.

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Toodle.java
> +        String allItemsSQL = "[:find ?eid ?uuid ?name " +
SQL?

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Toodle.java
> +                item.uuid().toString(),
Any reason why a UUID doesn't work here?

2018-03-29 22:34 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Toodle.java
> +        NativeResult result = JNA.INSTANCE.store_value_for_attribute(this.rawPointer, entid, attribute);
`store_value` is a pretty misleading name, no?

2018-03-29 22:34 UTC, rnewman commented on ios/Toodle/Extensions/Date+Int64.swift
> +        return Int64(self.timeIntervalSince1970 * 1000000)
If this is supposed to be a millisecond timestamp:

```
self.timeIntervalSince1970 * 1_000
```

If microseconds, use `1_000_000` and call this `toMicroseconds`.

2018-03-29 22:34 UTC, rnewman commented on ios/Toodle/Rust/List/Items/Item.swift
> +            return ToodleLib.sharedInstance.value(forAttribute: ":todo/due_date", onEntity: self.id!)?.asDate()
I think `ofEntity`, not `onEntity`.

2018-03-29 22:34 UTC, rnewman commented on ios/Toodle/Rust/Store/ResultList.swift
> +
…

2018-03-29 22:34 UTC, rnewman commented on ios/Toodle/Rust/Store/ResultRow.swift
> +    func get(index: Int32) -> TypedValue? {
Shouldn't these indices be `UInt`/`usize`?

2018-03-29 22:34 UTC, rnewman commented on ios/Toodle/Rust/ToodleLib.swift
> +        let allItemsSQL = """
SQL?

2018-03-29 22:34 UTC, rnewman commented on ios/Toodle/Rust/ToodleLib.swift
> +                        completion(items)
AIUI you only need a completion callback here because you're not using `Deferred`, right?

2018-03-29 22:34 UTC, rnewman commented on ios/Toodle/Rust/ToodleLib.swift
> +//        var dd: UnsafeMutablePointer<Int64>? = nil
TODO?

2018-03-29 22:34 UTC, rnewman commented on ios/Toodle/Rust/ToodleLib.swift
> +    func value(forAttribute attribute: String, onEntity entid: Int64) -> TypedValue? {
This PR is a bit hard for me to follow 'cos it's not clear what parts of it are pure Toodle hackery and which parts of it you want to keep around. This seems like it should be the latter, but it prints to stdout and is sitting in a file with a bunch of commented-out stuff…

2018-04-05 15:05 UTC, rnewman requested changes

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/Item.java
> +            TypedValue value = Toodle.getSharedInstance(null).valueForAttributeOnEntity(":todo/due_date", this.id);
Can we overload `getSharedInstance` to have a no-arg version, save passing that `null`?

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/Item.java
> +        dueDate = new Date(cal.getTimeInMillis() / 1000);
`Date(long millis)` — if you're calling`cal.getTimeInMillis()` then you don't need to divide by `1000`.

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/Item.java
> +            completionDate = new Date(timestamp / 1000);
What is `timestamp` here? Millis or micros?

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/ListAdapter.java
> +        if (date != null) {
I think you ought to do something even if `date` _is_ `null` — after all, completion dates can be removed. I'm not sure how this block is wrong, but I suspect it is.

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Query.java
> +            throw new NullPointerException("Query Builder consumed");
```
private void checkBuilder() {
    if (this.rawPointer == null) {
        throw new NullPointerException("Query builder consumed");
    }
}
```

```
void bindKeyword(String varName, String value) {
    this.checkBuilder();
    JNA.INSTANCE.…
}
```

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Query.java
> +        for(ResultRow row: rows) {
Nit: whitespace after `for`.

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Query.java
> +        rawPointer = null;
`this.rawPointer` for clarity.

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/QueryResultListHandler.java
> +package com.mozilla.toodle.rust;
Ahem.

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Toodle.java
> +        final String allItemsSQL = "[:find ?eid ?uuid ?name " +
SQL!

2018-04-05 15:05 UTC, rnewman commented on android/Toodle/app/src/main/java/com/mozilla/toodle/rust/Toodle.java
> +                             ":where "+
Alignment!

2018-04-06 09:09 UTC, fluffyemily commented on android/Toodle/app/src/main/java/com/mozilla/toodle/Item.java
> +            completionDate = new Date(timestamp / 1000);
micros

2022-01-14 20:04 UTC, closed without merging